from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a weekly maintenance report.")
    parser.add_argument("--audit-json", required=True, help="Path to repo-public-audit JSON output.")
    parser.add_argument("--output", required=True, help="Markdown report path to write.")
    args = parser.parse_args()

    audit_path = Path(args.audit_json)
    output_path = Path(args.output)
    audit = json.loads(audit_path.read_text(encoding="utf-8"))

    now_utc = datetime.now(timezone.utc)
    now_jst = now_utc.astimezone(ZoneInfo("Asia/Tokyo"))
    findings = audit.get("findings", [])
    severity_counts = count_severities(findings)
    commit = git_output(["rev-parse", "--short", "HEAD"])
    status = "pass" if severity_counts.get("high", 0) == 0 else "needs review"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_report(
            date_jst=now_jst.strftime("%Y-%m-%d"),
            generated_at=now_utc.strftime("%Y-%m-%d %H:%M:%S UTC"),
            commit=commit,
            status=status,
            severity_counts=severity_counts,
            finding_count=len(findings),
            highest=audit.get("highest_severity"),
        ),
        encoding="utf-8",
    )
    return 0


def count_severities(findings: list[dict[str, object]]) -> dict[str, int]:
    counts = {"high": 0, "medium": 0, "low": 0}
    for finding in findings:
        severity = str(finding.get("severity", ""))
        if severity in counts:
            counts[severity] += 1
    return counts


def git_output(args: list[str]) -> str:
    completed = subprocess.run(["git", *args], check=False, capture_output=True, text=True)
    if completed.returncode != 0:
        return "unknown"
    return completed.stdout.strip()


def render_report(
    *,
    date_jst: str,
    generated_at: str,
    commit: str,
    status: str,
    severity_counts: dict[str, int],
    finding_count: int,
    highest: str | None,
) -> str:
    return f"""# Weekly Maintenance Report - {date_jst}

Generated by GitHub Actions at {generated_at}.

## Check Summary

- Status: `{status}`
- Commit: `{commit}`
- Total findings: `{finding_count}`
- Highest severity: `{highest or "none"}`
- High: `{severity_counts["high"]}`
- Medium: `{severity_counts["medium"]}`
- Low: `{severity_counts["low"]}`

## Automated Checks

- Unit tests passed before this report was generated.
- Public-readiness audit ran with bounded Git history scanning.
- High-severity findings block the workflow.

## Next Maintainer Action

Work on the next open readiness issue:

- Add configurable allowlist rules.
- Add SARIF output for GitHub code scanning.
- Add example reports under `docs/examples/`.

This report is a maintenance artifact, not a substitute for meaningful code or documentation improvements.
"""


if __name__ == "__main__":
    raise SystemExit(main())

